resources:
  - name: repo
    type: GitRepo
    configuration:
      gitProvider: github_neha                     
      path: neha-mishraa/6080
      branches:
        include: ^main$
 
pipelines: 
  - name: Pipeline_S_DockerBuild_6080_0001
    configuration:
      environmentVariables:
        readOnly:
          env1: u20-install.jfrog-pipelines.com/docker-local/node
    steps:
      - name: S_DockerBuild_6080_0001
        type: DockerBuild
        execution:
          onStart:
            - echo "Preparing for work..."
        configuration:
          nodePool: k8sNodePool
          affinityGroup: BasicTest
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName:  $env1
          dockerImageTag: latest
          inputResources:
            - name: repo
